stages:
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  model_training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - src/models/train_model.py
    outs:
    - models

  flask_app:
    cmd: python src/app/app.py
    deps:
    - models
    - src/app/app.py
    - data/processed/df_final.csv
