stages:
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  model_training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - src/models/train_model.py
    outs:
    - models

  streamlit_app:
    cmd: streamlit run src/app/app.py
    deps:
    - models  # Assuming the Streamlit app depends on the trained models
    - src/app/app.py
    outs:
      - logs/streamlit.log
    
